### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by gingerbeardman** [Hakkin/PtDescreen#1]
Hi! Any chance of binary release?

I'd like to compare this against GIMP and Photoshop methods.

Thanks

**Comment by Hakkin** [comment]
Sorry, the code is non-functioning beyond detecting the screen parameters, I also haven't worked on it in a long time, I might work on it again some day, but currently I don't have time to do the research required to get everything working the way I want.

**Comment by gingerbeardman** [comment]
OK no problem, thanks anyway! good luck
